name = "kangxuan-grade3-math"
compatibility_date = "2026-10-07"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "muxin-grade3-db"
database_id = "0e711484-0b91-4d51-8b01-1d2b7dba8248"
